spring.application.name=bd2-mongodb-api

# String de Conexao com o MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://<USUARIO>:<SENHA>@cluster0.xxxx.mongodb.net/bd2_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true